import numpy as np
from collections import Counter
import matplotlib.pyplot as plt

b1 = ['banana_3', 'book_3', 'potato_3', 'band_aid_1', 'fork_5', 'banana_3', 'book_1', 'fork_4', 'allen_wrench_3', 'measuring_tape_3', 'shampoo_3', 'food_jar_4', 'marker_2', 'can_opener_2', 'syringe_3', 'prescription_medicine_bottle_2', 'soda_bottle_2', 'toothbrush_4', 'scissors_5', 'flashlight_2', 'fork_2', 'book_3', 'tissue_box_1', 'band_aid_3', 'water_bottle_3', 'soda_bottle_2', 'screwdriver_1', 'shampoo_2', 'onion_2', 'gauze_2', 'marker_1', 'medicine_bottle_5', 'picture_frame_3', 'toothbrush_5', 'shampoo_3', 'lemon_5', 'measuring_tape_4', 'cap_1', 'stapler_3', 'lightbulb_5', 'food_can_4', 'water_bottle_3', 'sponge_2', 'spoon_3', 'plate_1', 'apple_4', 'stapler_5', 'can_opener_3', 'apple_2', 'soda_bottle_3', 'toothbrush_2', 'medicine_bottle_4', 'lime_5', 'coffee_mug_1', 'marker_6', 'banana_4', 'flashlight_3', 'bowl_4', 'coffee_mug_1', 'soda_bottle_1', 'cell_phone_2', 'coffee_mug_4', 'eye_glasses_3', 'banana_4']
b1_obj = ['banana', 'book', 'potato', 'band_aid', 'fork', 'banana', 'book', 'fork', 'allen_wrench', 'measuring_tape', 'shampoo', 'food_jar', 'marker', 'can_opener', 'syringe', 'prescription_medicine_bottle', 'soda_bottle', 'toothbrush', 'scissors', 'flashlight', 'fork', 'book', 'tissue_box', 'band_aid', 'water_bottle', 'soda_bottle', 'screwdriver', 'shampoo', 'onion', 'gauze', 'marker', 'medicine_bottle', 'picture_frame', 'toothbrush', 'shampoo', 'lemon', 'measuring_tape', 'cap', 'stapler', 'lightbulb', 'food_can', 'water_bottle', 'sponge', 'spoon', 'plate', 'apple', 'stapler', 'can_opener', 'apple', 'soda_bottle', 'toothbrush', 'medicine_bottle', 'lime', 'coffee_mug', 'marker', 'banana', 'flashlight', 'bowl', 'coffee_mug', 'soda_bottle', 'cell_phone', 'coffee_mug', 'eye_glasses', 'banana']

b2 = ['sponge_2', 'stapler_3', 'shampoo_4', 'banana_4', 'plate_4', 'plate_2', 'eye_glasses_2', 'stapler_1', 'cell_phone_3', 'stapler_1', 'scissors_4', 'plate_2', 'hand_towel_1', 'pliers_2', 'spoon_2', 'bowl_3', 'shampoo_5', 'marker_5', 'syringe_2', 'scissors_6', 'allen_wrench_1', 'bowl_5', 'cap_2', 'syringe_3', 'plate_1', 'hammer_2', 'hammer_6', 'onion_5', 'cell_phone_3', 'pencil_3', 'sponge_1', 'potato_1', 'potato_3', 'picture_frame_1', 'pencil_4', 'toothbrush_1', 'stapler_5', 'coffee_mug_1', 'coffee_mug_3', 'lime_5', 'toothpaste_3', 'book_5', 'lightbulb_2', 'marker_1', 'pencil_3', 'prescription_medicine_bottle_2', 'bell_pepper_1', 'syringe_2', 'cell_phone_3', 'cell_phone_1', 'fork_5', 'bowl_2', 'pencil_1', 'water_bottle_1', 'lightbulb_3', 'pliers_1', 'bowl_1', 'lemon_1', 'spoon_5', 'picture_frame_4', 'bell_pepper_1', 'syringe_2', 'cell_phone_2', 'hand_towel_2']
b2_obj = ['sponge', 'stapler', 'shampoo', 'banana', 'plate', 'plate', 'eye_glasses', 'stapler', 'cell_phone', 'stapler', 'scissors', 'plate', 'hand_towel', 'pliers', 'spoon', 'bowl', 'shampoo', 'marker', 'syringe', 'scissors', 'allen_wrench', 'bowl', 'cap', 'syringe', 'plate', 'hammer', 'hammer', 'onion', 'cell_phone', 'pencil', 'sponge', 'potato', 'potato', 'picture_frame', 'pencil', 'toothbrush', 'stapler', 'coffee_mug', 'coffee_mug', 'lime', 'toothpaste', 'book', 'lightbulb', 'marker', 'pencil', 'prescription_medicine_bottle', 'bell_pepper', 'syringe', 'cell_phone', 'cell_phone', 'fork', 'bowl', 'pencil', 'water_bottle', 'lightbulb', 'pliers', 'bowl', 'lemon', 'spoon', 'picture_frame', 'bell_pepper', 'syringe', 'cell_phone', 'hand_towel']

b3 = ['water_bottle_1', 'soda_bottle_4', 'band_aid_2', 'scissors_3', 'banana_5', 'lime_4', 'spoon_5', 'water_bottle_3', 'shampoo_1', 'toothpaste_2', 'pliers_2', 'potato_3', 'pliers_2', 'lemon_1', 'fork_4', 'allen_wrench_1', 'book_3', 'soda_bottle_3', 'notebook_2', 'spoon_5', 'allen_wrench_3', 'food_can_5', 'shampoo_1', 'can_opener_1', 'water_bottle_1', 'toothpaste_1', 'lightbulb_2', 'book_4', 'banana_4', 'bell_pepper_3', 'bell_pepper_1', 'spoon_5', 'potato_5', 'pliers_1', 'apple_3', 'measuring_tape_2', 'lemon_5', 'potato_3', 'coffee_mug_5', 'lightbulb_4', 'coffee_mug_3', 'picture_frame_1', 'pliers_2', 'bowl_1', 'gauze_1', 'fork_3', 'scissors_3', 'toothbrush_2', 'measuring_tape_5', 'allen_wrench_5', 'toothpaste_2', 'syringe_3', 'bell_pepper_5', 'band_aid_5', 'toothpaste_1', 'screwdriver_3', 'food_can_2', 'apple_1', 'lemon_1', 'food_can_5', 'food_can_5', 'apple_5', 'lightbulb_2', 'potato_5']
b3_obj = ['water_bottle', 'soda_bottle', 'band_aid', 'scissors', 'banana', 'lime', 'spoon', 'water_bottle', 'shampoo', 'toothpaste', 'pliers', 'potato', 'pliers', 'lemon', 'fork', 'allen_wrench', 'book', 'soda_bottle', 'notebook', 'spoon', 'allen_wrench', 'food_can', 'shampoo', 'can_opener', 'water_bottle', 'toothpaste', 'lightbulb', 'book', 'banana', 'bell_pepper', 'bell_pepper', 'spoon', 'potato', 'pliers', 'apple', 'measuring_tape', 'lemon', 'potato', 'coffee_mug', 'lightbulb', 'coffee_mug', 'picture_frame', 'pliers', 'bowl', 'gauze', 'fork', 'scissors', 'toothbrush', 'measuring_tape', 'allen_wrench', 'toothpaste', 'syringe', 'bell_pepper', 'band_aid', 'toothpaste', 'screwdriver', 'food_can', 'apple', 'lemon', 'food_can', 'food_can', 'apple', 'lightbulb', 'potato']

b4 = ['can_opener_3', 'spoon_1', 'spoon_4', 'stapler_1', 'apple_4', 'can_opener_4', 'plate_2', 'food_jar_2', 'cap_2', 'pliers_2', 'screwdriver_1', 'hand_towel_3', 'hand_towel_2', 'mouse_1', 'apple_5', 'band_aid_4', 'food_jar_1', 'spoon_2', 'toothbrush_3', 'food_can_4', 'shampoo_4', 'flashlight_3', 'scissors_4', 'scissors_4', 'plate_5', 'book_3', 'mouse_3', 'food_can_4', 'marker_5', 'notebook_1', 'food_jar_2', 'book_2', 'hammer_5', 'band_aid_2', 'prescription_medicine_bottle_2', 'lime_5', 'allen_wrench_1', 'picture_frame_1', 'apple_4', 'screwdriver_1', 'onion_3', 'screwdriver_5', 'pill_cutter_1', 'potato_4', 'band_aid_2', 'flashlight_3', 'lemon_5', 'water_bottle_1', 'bowl_4', 'apple_3', 'soda_bottle_5', 'band_aid_4', 'picture_frame_1', 'pliers_3', 'pencil_2', 'can_opener_5', 'hammer_2', 'lemon_2', 'sponge_2', 'hand_towel_2', 'coffee_mug_3', 'pill_cutter_1', 'toothbrush_2', 'shampoo_3']
b4_obj = ['can_opener', 'spoon', 'spoon', 'stapler', 'apple', 'can_opener', 'plate', 'food_jar', 'cap', 'pliers', 'screwdriver', 'hand_towel', 'hand_towel', 'mouse', 'apple', 'band_aid', 'food_jar', 'spoon', 'toothbrush', 'food_can', 'shampoo', 'flashlight', 'scissors', 'scissors', 'plate', 'book', 'mouse', 'food_can', 'marker', 'notebook', 'food_jar', 'book', 'hammer', 'band_aid', 'prescription_medicine_bottle', 'lime', 'allen_wrench', 'picture_frame', 'apple', 'screwdriver', 'onion', 'screwdriver', 'pill_cutter', 'potato', 'band_aid', 'flashlight', 'lemon', 'water_bottle', 'bowl', 'apple', 'soda_bottle', 'band_aid', 'picture_frame', 'pliers', 'pencil', 'can_opener', 'hammer', 'lemon', 'sponge', 'hand_towel', 'coffee_mug', 'pill_cutter', 'toothbrush', 'shampoo']

b5 = ['lime_5', 'food_jar_5', 'allen_wrench_4', 'book_5', 'bell_pepper_3', 'eye_glasses_3', 'hammer_2', 'screwdriver_3', 'medicine_bottle_1', 'toothbrush_3', 'screwdriver_4', 'shampoo_1', 'toothpaste_5', 'medicine_bottle_3', 'lemon_5', 'medicine_bottle_3', 'lime_1', 'syringe_3', 'lemon_1', 'picture_frame_2', 'scissors_2', 'food_jar_1', 'allen_wrench_2', 'lime_1', 'food_jar_1', 'marker_1', 'onion_1', 'can_opener_2', 'hammer_1', 'stapler_3', 'notebook_2', 'spoon_2', 'bell_pepper_5', 'coffee_mug_2', 'plate_2', 'measuring_tape_1', 'hammer_5', 'fork_4', 'gauze_1', 'screwdriver_1', 'prescription_medicine_bottle_3', 'eye_glasses_3', 'mouse_3', 'banana_4', 'scissors_5', 'onion_3', 'marker_1', 'hammer_6', 'marker_1', 'picture_frame_1', 'can_opener_2', 'onion_3', 'potato_5', 'toothpaste_1', 'pliers_2', 'medicine_bottle_3', 'eye_glasses_4', 'cap_2', 'soda_bottle_1', 'marker_3', 'scissors_3', 'measuring_tape_3', 'hammer_2', 'lightbulb_5']
b5_obj = ['lime', 'food_jar', 'allen_wrench', 'book', 'bell_pepper', 'eye_glasses', 'hammer', 'screwdriver', 'medicine_bottle', 'toothbrush', 'screwdriver', 'shampoo', 'toothpaste', 'medicine_bottle', 'lemon', 'medicine_bottle', 'lime', 'syringe', 'lemon', 'picture_frame', 'scissors', 'food_jar', 'allen_wrench', 'lime', 'food_jar', 'marker', 'onion', 'can_opener', 'hammer', 'stapler', 'notebook', 'spoon', 'bell_pepper', 'coffee_mug', 'plate', 'measuring_tape', 'hammer', 'fork', 'gauze', 'screwdriver', 'prescription_medicine_bottle', 'eye_glasses', 'mouse', 'banana', 'scissors', 'onion', 'marker', 'hammer', 'marker', 'picture_frame', 'can_opener', 'onion', 'potato', 'toothpaste', 'pliers', 'medicine_bottle', 'eye_glasses', 'cap', 'soda_bottle', 'marker', 'scissors', 'measuring_tape', 'hammer', 'lightbulb']

b6 = ['pliers_4', 'eye_glasses_2', 'food_can_2', 'pencil_2', 'toothpaste_5', 'lightbulb_1', 'flashlight_2', 'hammer_4', 'onion_3', 'syringe_1', 'potato_4', 'bowl_4', 'onion_3', 'hand_towel_1', 'bowl_4', 'lime_1', 'measuring_tape_5', 'banana_4', 'book_3', 'marker_1', 'lime_3', 'allen_wrench_4', 'medicine_bottle_5', 'toothpaste_2', 'scissors_5', 'medicine_bottle_5', 'fork_4', 'mouse_2', 'toothbrush_5', 'plate_5', 'syringe_3', 'food_jar_2', 'band_aid_2', 'medicine_bottle_4', 'banana_2', 'apple_5', 'mouse_3', 'pencil_4', 'bowl_4', 'lemon_2', 'fork_1', 'hammer_1', 'stapler_4', 'prescription_medicine_bottle_3', 'onion_3', 'bell_pepper_2', 'can_opener_4', 'food_jar_1', 'pencil_3']
b6_obj = ['pliers', 'eye_glasses', 'food_can', 'pencil', 'toothpaste', 'lightbulb', 'flashlight', 'hammer', 'onion', 'syringe', 'potato', 'bowl', 'onion', 'hand_towel', 'bowl', 'lime', 'measuring_tape', 'banana', 'book', 'marker', 'lime', 'allen_wrench', 'medicine_bottle', 'toothpaste', 'scissors', 'medicine_bottle', 'fork', 'mouse', 'toothbrush', 'plate', 'syringe', 'food_jar', 'band_aid', 'medicine_bottle', 'banana', 'apple', 'mouse', 'pencil', 'bowl', 'lemon', 'fork', 'hammer', 'stapler', 'prescription_medicine_bottle', 'onion', 'bell_pepper', 'can_opener', 'food_jar', 'pencil']

all_batch_instances = [b1, b2, b3, b4, b5, b6]
all_batch_objects = [b1_obj, b2_obj, b3_obj, b4_obj, b5_obj, b6_obj]



for i in range(len(all_batch_objects)):
    all_batch_objects[i] = Counter(all_batch_objects[i])
    
    fig = plt.figure(figsize=(25,20))
    plt.bar(all_batch_objects[i].keys(), all_batch_objects[i].values())
    plt.xticks(rotation=90)
    plt.savefig('result-analysis/inspect-supcon-batch-'+str(i)+'.png')

    fig2 = plt.figure(figsize=(25,20))
    plt.bar(all_batch_objects[i].keys(), len(all_batch_instances[i]) - np.array(list(all_batch_objects[i].values())))
    plt.xticks(rotation=90)
    plt.savefig('result-analysis/inspect-supcon-batch-negatives-'+str(i)+'.png')